import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import { Header } from './components/Header';
import { Sidebar } from './components/Sidebar';
import { Footer } from './components/Footer';

import styles from './MainLayout.module.css';
import './globals.css';

const noto_sans = Noto_Sans_KR({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Changed Title from meta',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={noto_sans.className}>
        <div className={styles.wrapper}>
          <Header className={styles.header}>Content Header</Header>
          <Sidebar className={styles.sidebar}>Content Sidebar</Sidebar>
          <div className={styles.body}>{children}</div>
          <Footer className={styles.footer}>Content Footer</Footer>
        </div>
      </body>
    </html>
  );
}
